### ISSUE TITLE
Towards eden v(0.)2.x

### ISSUE THREAD

**Issue by prog893** [baikonur-oss/aws-eden-cli#4]
- [x] `eden config push` - #3 
- [x] `eden config pull` #12 
- [x] `eden config remote-rm` #5 
- [x] `eden config ls` #12 
- [x] `eden ls` #7 
- [x] stateful create/delete #8
